[all]
parking-demo.swedencentral.cloudapp.azure.com ansible_user=azureuser ansible_ssh_private_key_file=/mnt/c/Users/tdimopoulos/Downloads/it214145_key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
